"""add comments table and questions accepted_answer_id

Revision ID: 124cca2a07aa
Revises: 17387cd127e2
Create Date: 2026-09-22 17:24:55.664727

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision: str = '124cca2a07aa'
down_revision: str | None = '17387cd127e2'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(
        'ix_comments_target_created', 'comments',
        ['target_type', 'target_id', 'created_at'], unique=False
    )
    op.add_column('questions', sa.Column('accepted_answer_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_questions_accepted_answer', 'questions', 'answers',
        ['accepted_answer_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_questions_accepted_answer', 'questions', type_='foreignkey')
    op.drop_column('questions', 'accepted_answer_id')
    op.drop_index('ix_comments_target_created', table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
