"""add answers and votes tables

Revision ID: 17387cd127e2
Revises: 346e395dfea8
Create Date: 2026-09-22 14:04:37.185127

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision: str = '17387cd127e2'
down_revision: str | None = '346e395dfea8'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_votes_target', 'votes', ['target_type', 'target_id'], unique=False)
    op.create_index(
        'uq_votes_user_target', 'votes',
        ['user_id', 'target_type', 'target_id'], unique=True
    )
    op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_author_id'), 'answers', ['author_id'], unique=False)
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_author_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index('uq_votes_user_target', table_name='votes')
    op.drop_index('ix_votes_target', table_name='votes')
    op.drop_table('votes')
    # ### end Alembic commands ###
