"""add questions table

Revision ID: 346e395dfea8
Revises: ab3c0dd6dd38
Create Date: 2026-09-10 20:36:20.800757

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision: str = '346e395dfea8'
down_revision: str | None = 'ab3c0dd6dd38'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_author_id'), 'questions', ['author_id'], unique=False)
    op.create_index(op.f('ix_questions_created_at'), 'questions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_created_at'), table_name='questions')
    op.drop_index(op.f('ix_questions_author_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
