"""add questions status column

Revision ID: 46411f564ffa
Revises: f98c1b725e11
Create Date: 2026-09-29 09:46:45.013722

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision: str = '46411f564ffa'
down_revision: str | None = 'f98c1b725e11'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'questions',
        sa.Column('status', sa.String(length=10), server_default='open', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'status')
    # ### end Alembic commands ###
